---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmf-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acmf-frontend
  template:
    metadata:
      labels:
        app: acmf-frontend
    spec:
      containers:
      - name: acmf-frontend
        image: 637423430820.dkr.ecr.us-east-1.amazonaws.com/acmf-frontend:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: acmf-frontend-service
spec:
  selector:
    app: acmf-frontend
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer